package com.nextenti.services.core.service.road;
import com.nextenti.services.common.exception.*;import com.nextenti.services.core.dto.road.*;import com.nextenti.services.core.service.organization.OrganizationService;import com.nextenti.services.domain.entity.*;import com.nextenti.services.domain.repository.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.*;import java.util.*;
@Service public class RoadService {private final RoadRepository roads;private final RoadSectionRepository sections;private final ProjectRepository projects;private final OrganizationService orgs;public RoadService(RoadRepository r,RoadSectionRepository s,ProjectRepository p,OrganizationService o){roads=r;sections=s;projects=p;orgs=o;}
@Transactional public RoadResponse create(UUID u,UUID projectId,RoadRequest r)throws SmartRoadException{ProjectEntity p=project(u,projectId);RoadEntity x=new RoadEntity();x.setId(UUID.randomUUID());x.setProjectId(p.getId());x.setCreatedBy(u);x.setModifiedBy(u);apply(x,r);return map(roads.save(x));}
@Transactional(readOnly=true)public List<RoadResponse> list(UUID u,UUID projectId)throws SmartRoadException{project(u,projectId);return roads.findByProjectId(projectId).stream().map(this::map).toList();}
@Transactional(readOnly=true)public RoadResponse get(UUID u,UUID id)throws SmartRoadException{RoadEntity r=road(id);project(u,r.getProjectId());return map(r);}
@Transactional public RoadResponse update(UUID u,UUID id,RoadRequest r)throws SmartRoadException{RoadEntity x=road(id);project(u,x.getProjectId());apply(x,r);x.setModifiedBy(u);return map(roads.save(x));}
@Transactional public void delete(UUID u,UUID id)throws SmartRoadException{RoadEntity r=road(id);project(u,r.getProjectId());roads.delete(r);}
@Transactional public RoadSectionResponse createSection(UUID u,UUID roadId,RoadSectionRequest r)throws SmartRoadException{RoadEntity road=road(roadId);project(u,road.getProjectId());RoadSectionEntity s=new RoadSectionEntity();s.setId(UUID.randomUUID());s.setRoadId(roadId);s.setCreatedBy(u);s.setModifiedBy(u);apply(s,r);return sectionMap(sections.save(s));}
@Transactional(readOnly=true)public List<RoadSectionResponse> listSections(UUID u,UUID roadId)throws SmartRoadException{RoadEntity r=road(roadId);project(u,r.getProjectId());return sections.findByRoadId(roadId).stream().map(this::sectionMap).toList();}
private ProjectEntity project(UUID u,UUID id)throws SmartRoadException{ProjectEntity p=projects.findById(id).orElseThrow(()->notFound("project.not.found"));orgs.requireMember(u,p.getOrganizationId());return p;}private RoadEntityEntity road(UUID id)throws SmartRoadException{return roads.findById(id).orElseThrow(()->notFound("road.not.found"));}private SmartRoadException notFound(String x){return new SmartRoadException(ApplicationLayer.SERVICE_LAYER,ErrorCodeMapping.DAO_NOT_FOUND,x);}
private void apply(RoadEntity x,RoadRequest r)throws SmartRoadException{BigDecimal c=r.completedLengthM()==null?BigDecimal.ZERO:r.completedLengthM();if(c.compareTo(r.lengthM())>0)throw new SmartRoadException(ApplicationLayer.SERVICE_LAYER,ErrorCodeMapping.SERVICE_VALIDATION_FAILED,"road.completed.length.invalid");x.setName(r.name());x.setLengthM(r.lengthM());x.setWidthM(r.widthM());x.setThicknessMm(r.thicknessMm());x.setStartChainage(r.startChainage());x.setEndChainage(r.endChainage());x.setCompletedLengthM(c);}private void apply(RoadSectionEntity x,RoadSectionRequest r)throws SmartRoadException{BigDecimal c=r.completedLengthM()==null?BigDecimal.ZERO:r.completedLengthM();if(c.compareTo(r.lengthM())>0)throw new SmartRoadException(ApplicationLayer.SERVICE_LAYER,ErrorCodeMapping.SERVICE_VALIDATION_FAILED,"road.section.completed.length.invalid");x.setStartChainage(r.startChainage());x.setEndChainage(r.endChainage());x.setLengthM(r.lengthM());x.setCompletedLengthM(c);}
private RoadEntityResponse map(RoadEntity x){BigDecimal rem=x.getLengthM().subtract(x.getCompletedLengthM());return new RoadResponse(x.getId(),x.getProjectId(),x.getName(),x.getLengthM(),x.getWidthM(),x.getThicknessMm(),x.getStartChainage(),x.getEndChainage(),x.getCompletedLengthM(),rem,x.getCompletedLengthM().multiply(BigDecimal.valueOf(100)).divide(x.getLengthM(),2,RoundingMode.HALF_UP));}private RoadEntitySectionResponse sectionMap(RoadSectionEntity x){BigDecimal rem=x.getLengthM().subtract(x.getCompletedLengthM());return new RoadSectionResponse(x.getId(),x.getRoadId(),x.getStartChainage(),x.getEndChainage(),x.getLengthM(),x.getCompletedLengthM(),rem,x.getCompletedLengthM().multiply(BigDecimal.valueOf(100)).divide(x.getLengthM(),2,RoundingMode.HALF_UP));}}
