package com.nextenti.services.core.service.project;
import com.nextenti.services.common.exception.*;import com.nextenti.services.core.dto.project.*;import com.nextenti.services.core.service.organization.OrganizationService;import com.nextenti.services.domain.entity.ProjectEntity;import com.nextenti.services.domain.repository.ProjectRepository;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.math.BigDecimal;import java.util.*;
@Service public class ProjectService {private final ProjectRepository projects;private final OrganizationService orgs;public ProjectService(ProjectRepository p,OrganizationService o){projects=p;orgs=o;}
@Transactional public ProjectResponse create(UUID u,ProjectRequest r)throws SmartRoadException{orgs.requireMember(u,r.organizationId());ProjectEntity p=new ProjectEntity();p.setId(UUID.randomUUID());p.setOrganizationId(r.organizationId());p.setCreatedBy(u);p.setModifiedBy(u);apply(p,r);return map(projects.save(p));}
@Transactional(readOnly=true)public List<ProjectResponse> list(UUID u,UUID org)throws SmartRoadException{orgs.requireMember(u,org);return projects.findByOrganizationIdAndArchivedFalse(org).stream().map(this::map).toList();}
@Transactional(readOnly=true)public ProjectResponse get(UUID u,UUID id,UUID org)throws SmartRoadException{return map(find(u,id,org));}
@Transactional public ProjectResponse update(UUID u,UUID id,ProjectRequest r)throws SmartRoadException{ProjectEntity p=find(u,id,r.organizationId());apply(p,r);p.setModifiedBy(u);return map(projects.save(p));}
@Transactional public void archive(UUID u,UUID id,UUID org)throws SmartRoadException{ProjectEntity p=find(u,id,org);p.setArchived(true);p.setModifiedBy(u);projects.save(p);}
private ProjectEntity find(UUID u,UUID id,UUID org)throws SmartRoadException{orgs.requireMember(u,org);return projects.findByIdAndOrganizationIdAndArchivedFalse(id,org).orElseThrow(()->new SmartRoadException(ApplicationLayer.SERVICE_LAYER,ErrorCodeMapping.DAO_NOT_FOUND,"project.not.found"));}
private void apply(ProjectEntity p,ProjectRequest r){p.setClientId(r.clientId());p.setCode(r.code());p.setName(r.name());p.setDescription(r.description());p.setLocation(r.location());p.setStatus(r.status());p.setBudget(r.budget());p.setProgress(r.progress()==null?BigDecimal.ZERO:r.progress());p.setStartDate(r.startDate());p.setEndDate(r.endDate());}
private ProjectEntityResponse map(ProjectEntity p){return new ProjectResponse(p.getId(),p.getOrganizationId(),p.getClientId(),p.getCode(),p.getName(),p.getDescription(),p.getLocation(),p.getStatus(),p.getBudget(),p.getActualCost(),p.getProgress(),p.getStartDate(),p.getEndDate(),Boolean.TRUE.equals(p.getArchived()));}}
