CREATE TABLE boqs (
 id UUID PRIMARY KEY, project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE, created_by UUID NOT NULL REFERENCES sr_users(id), date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, modified_by UUID NOT NULL REFERENCES sr_users(id), date_modified TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, db_version INTEGER NOT NULL DEFAULT 1, name VARCHAR(255) NOT NULL, description TEXT
);
CREATE TABLE boq_items (
 id UUID PRIMARY KEY, boq_id UUID NOT NULL REFERENCES boqs(id) ON DELETE CASCADE, created_by UUID NOT NULL REFERENCES sr_users(id), date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, modified_by UUID NOT NULL REFERENCES sr_users(id), date_modified TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP, db_version INTEGER NOT NULL DEFAULT 1, item_code VARCHAR(100), description TEXT NOT NULL, unit VARCHAR(32) NOT NULL, estimated_quantity NUMERIC(18,3) NOT NULL, rate NUMERIC(18,2) NOT NULL, actual_quantity NUMERIC(18,3) NOT NULL DEFAULT 0, actual_rate NUMERIC(18,2)
);
